---
title: "Sales Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup}
library(flexdashboard)
library(shiny)
library(shinyWidgets)
library(DT)

# Cor
library(tidyverse)
library(lubridate)

# Interactive Visualizations
library(plotly)
library(ggplot2)

# Spatial Data
library(raster)
library(sf)

knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())


```

``` {r}
#function for currency formatting:
format_to_euro <-
function(x, suffix = " €") {
  
  scales::dollar(x,
                 suffix       = suffix,
                 prefix       = "",
                 big.mark     = ".",
                 decimal.mark = ",")
}
euro_format <-
function(scale        = 1,
                        prefix       = "",
                        suffix       = " €",
                        big.mark     = ".",
                        decimal.mark = ",") {
  
  scales::dollar_format(suffix       = suffix,
                        prefix       = prefix,
                        big.mark     = big.mark,
                        decimal.mark = decimal.mark,
                        scale        = scale)
  
}

```

```{r}

# Bike data
bikes_tbl      <- readRDS("data/bikes_tbl.rds")
bikeshops_tbl  <- readRDS("data/bikeshops_tbl.rds")
orderlines_tbl <- readRDS("data/orderlines_tbl.rds")

bike_orderlines_tbl <- orderlines_tbl %>%
    left_join(bikes_tbl,     by = c("product_id" = "bike_id")) %>%
    left_join(bikeshops_tbl, by = c("customer_id" = "bikeshop_id")) %>%
    mutate(total_price = price_euro * quantity)

# German spatial data
germany_sp <- getData('GADM', country='DE', level=1) 
# Convert SpatialPolygonsDataFrame to an sf dataframe
germany_sf <- st_as_sf(germany_sp) %>% 
                  # Add english names
                  mutate(VARNAME_1 = ifelse(is.na(VARNAME_1), NAME_1, VARNAME_1)) 


category_1_labels <- bike_orderlines_tbl %>%
  dplyr::select(category_1) %>% unique() %>% c()

category_2_labels <- bike_orderlines_tbl %>% dplyr::filter(category_1 %in% category_1_labels[[1]]) %>% 
  dplyr::select(category_2) %>% unique() %>% c()
```



Sidebar {.sidebar}
------------------------

```{r}
# Inputs
default_min_date = "2015-01-01"
default_max_date = today()

default_category_1 = category_1_labels[[1]][1]

dateRangeInput(inputId = "date_range", 
               label   = h4("Date Range"), 
               start   = default_min_date, 
               end     = default_max_date,        
               min     = min(bike_orderlines_tbl$date), 
               max     = max(bike_orderlines_tbl$date), 
               startview = "year")

checkboxGroupButtons( # or radioGroupButtons
  inputId = "bike_type_group",
  label = h4("Bike Type: "),
  checkIcon = list(
      yes = icon("square-check"),
      no = icon("square")),
  choices = category_1_labels[[1]],
  selected = default_category_1
)


default_category_2 = bike_orderlines_tbl %>% dplyr::filter(category_1 %in% default_category_1) %>% 
  dplyr::select(category_2) %>% unique() %>% c()
default_category_2 = default_category_2[[1]]

pickerInput(
  inputId = "bike_family_group", 
  label = h4("Bike Family:"), 
  #choices = bike_orderlines_tbl %>% dplyr::filter(category_1 %in% default_category_1) %>% 
  #  dplyr::select(category_2) %>% unique() %>% c(), 
  choices = category_2_labels[[1]],
  options = pickerOptions(
    actionsBox = TRUE, 
    size = 10,
    selectedTextFormat = "count > 3"
  ), 
  selected = default_category_2,
  multiple = TRUE
)

 # observe({
 #    x <- input$bike_type_group
 # 
 #    # Can use character(0) to remove all choices
 #    if (is.null(x))
 #      x <- character(0)
 # 
 #    # Can also set the label and select items
 #    updateSelectInput(session=session, 
 #                      inputId = "bike_family_group",
 #      choices =  bike_orderlines_tbl %>% dplyr::filter(category_1 %in% x) %>% 
 #    dplyr::select(category_2) %>% unique() %>% c(),
 #    )
 #  })

# actionButton(inputId = "apply",
#              h4(label = "Apply"),
#              icon = icon("play"))

# plot map of german states with corresponding coloring

actionButton(inputId = "reset",
             h4(label   = "Reset"),
             icon    = icon("sync"))
observeEvent(eventExpr = input$reset, handlerExpr = {
  updateDateRangeInput(session= session,
                           inputId = "date_range",
                           start = default_min_date,
                           end = default_max_date)
  
  updateCheckboxGroupButtons(session = session,
                            inputId = "bike_type_group",
                            selected = default_category_1)

  updatePickerInput(session = session,
                    inputId = "bike_family_group",
                    selected = default_category_2)

})

```



Column {data-width=1000}
---------------------------------------------------------------

### By State
```{r}
# get Data by state
geo_plot_tbl_filtered_reactive <- reactive({
 bike_orderlines_tbl %>%
    dplyr::filter(category_1 %in% input$bike_type_group) %>%
    dplyr::filter(category_2 %in% input$bike_family_group) %>%
    dplyr::filter(order_date > input$date_range[1]) %>%
    dplyr::filter(order_date < input$date_range[2]) %>%
    group_by(state) %>%
    summarise(total_revenue = sum(total_price)) %>%
                  ungroup() %>%
                  right_join(germany_sf, by = c("state" = "VARNAME_1")) %>%
                  mutate(total_revenue = ifelse(is.na(total_revenue), 0, total_revenue)) %>%
                  mutate(label_text = str_glue("State: {state}
                                         Revenue: {format_to_euro(total_revenue)}")) %>%
                  # Convert back to an sf object, that can be plotted
                  st_as_sf()
})
```

```{r}


#observeEvent(eventExpr = input$apply, handlerExpr = {
plotlyOutput(outputId = "map_plot")
# plot map of german states with corresponding coloring
output$map_plot <- renderPlotly({
  plot_ly(geo_plot_tbl_filtered_reactive(),
          split      = ~NAME_1,
          color      = ~total_revenue,
          colors     = "Blues",
          stroke     = I("black"),
          hoverinfo  = 'text',
          text       = ~label_text,
          hoveron    = "fills",
          showlegend = FALSE)
})
#})
```

Column {data-width=1000}
---------------------------------------------------------------

### Over Time
``` {r}
    
radioGroupButtons(
  inputId = "time_unit_group",
  label = h4("Time Unit: "),
  checkIcon = list(
      yes = icon("square-check")),
  choices = c("D"="day", "W"="week", "M"="month", "Q"="quarter", "Y"="year"),
  selected = "month"
)

```

``` {r}


sales_data_reactive <-reactive({
  # Handle Data
date_format = switch(input$time_unit_group,
       "day"="%B %d %Y",
       "week"="%W %Y",
       "month"="%B %Y",
       "year"="%Y"
       )

      
data_tbl <- bike_orderlines_tbl %>%
    dplyr::filter(category_1 %in% input$bike_type_group) %>%
    dplyr::filter(category_2 %in% input$bike_family_group) %>%
    dplyr::filter(order_date > input$date_range[1]) %>%
    dplyr::filter(order_date < input$date_range[2]) %>%

    dplyr::select(order_date, total_price) %>%
    
    mutate(date_rounded = floor_date(order_date, unit = input$time_unit_group)) %>%
    
    group_by(date_rounded) %>%
    summarise(total_sales = sum(total_price)) %>%
    ungroup() %>%
    
    mutate(label_text = str_glue("Sales: {format_to_euro(total_sales)}
                                 Date: {date_rounded %>% format(date_format)}"))
  return(data_tbl)
})

```

```{r}
plot_total_sales_reactive <-reactive({
  # Handle Data
  data_tbl <- bike_orderlines_tbl %>%
    dplyr::filter(category_1 %in% input$bike_type_group) %>%
    dplyr::filter(category_2 %in% input$bike_family_group) %>%
    dplyr::filter(order_date > input$date_range[1]) %>%
    dplyr::filter(order_date < input$date_range[2]) %>%
    
    dplyr::select(order_date, total_price) %>%
    
    mutate(date_rounded = floor_date(order_date, unit = unit)) %>%
    
    group_by(date_rounded) %>%
    summarise(total_sales = sum(total_price)) %>%
    ungroup() %>%
    
    mutate(label_text = str_glue("Sales: {format_to_euro(total_sales)}
                                 Date: {date_rounded %>% format(date_format)}"))
  
  # Make Plot
  g1 <- data_tbl %>%
    ggplot(aes(x = date_rounded, y = total_sales)) +
    
    # Geoms
    geom_point(aes(text = label_text), color = "#2C3E50") +
    geom_smooth(method = "loess", span = 0.2) +
    
    # Formatting
    scale_y_continuous(labels = euro_format()) +
    expand_limits(y = 0) +
    labs(
      title = "Total Sales",
      y = "Revenue (Euro)",
      x = ""
    )
  
  return (g1)
})
```

```{r}


#observeEvent(eventExpr = input$apply, handlerExpr = {
plotlyOutput(outputId = "data_graph")
output$data_graph <- renderPlotly({
  print(sales_data_reactive)
  p <- ggplot(sales_data_reactive(), aes(x = date_rounded, y = total_sales)) +

    # Geoms
    geom_point(aes(text = label_text), color = "#2C3E50") +
    geom_smooth(method = "loess", span = 0.2) +

    # Formatting
    scale_y_continuous(labels = euro_format()) +
    expand_limits(y = 0) +
    labs(
      title = "Total Sales",
      y = "Revenue (Euro)",
      x = ""
    )
  p_ly <- ggplotly(p, tooltip = "text")
  #ggplotly(plot_total_sales_reactive(), tooltip = "text")

})
#})
```



